// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uptime.Workflows.Core.Data;

#nullable disable

namespace Uptime.Workflows.Core.Data.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    partial class WorkflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("UptimeAPI")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Uptime.Workflows.Core.Data.OutboundNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ResponseBody")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UniqueKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("UniqueKey")
                        .IsUnique();

                    b.HasIndex("EventName", "Status");

                    b.ToTable("OutboundNotifications", "UptimeAPI");
                });

            modelBuilder.Entity("Uptime.Workflows.Core.Data.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedByPrincipalId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DeletedByPrincipalId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InitiatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Outcome")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StorageJson")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedByPrincipalId")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InitiatedById");

                    b.HasIndex("WorkflowTemplateId");

                    b.ToTable("Workflows", "UptimeAPI");
                });

            modelBuilder.Entity("Uptime.Workflows.Core.Data.WorkflowHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("Event")
                        .HasColumnType("int");

                    b.Property<DateTime>("Occurred")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerformedById")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformedById");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowHistories", "UptimeAPI");
                });

            modelBuilder.Entity("Uptime.Workflows.Core.Data.WorkflowPrincipal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeactivatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LoginName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("SyncedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkflowPrincipals", "UptimeAPI");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "klient1@example.com",
                            ExternalId = "S-1-5-21-10001",
                            Name = "Klient Üks",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "klient2@example.com",
                            ExternalId = "S-1-5-21-10002",
                            Name = "Klient Kaks",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "klient3@example.com",
                            ExternalId = "S-1-5-21-10003",
                            Name = "Klient Kolm",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "klient4@example.com",
                            ExternalId = "S-1-5-21-10004",
                            Name = "Klient Neli",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "klient5@example.com",
                            ExternalId = "S-1-5-21-10005",
                            Name = "Klient Viis",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "marika.oja@example.com",
                            ExternalId = "S-1-5-21-10006",
                            Name = "Marika Oja",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "jana.parn@example.com",
                            ExternalId = "S-1-5-21-10007",
                            Name = "Jana Pärn",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "piia.saar@example.com",
                            ExternalId = "S-1-5-21-10008",
                            Name = "Piia Saar",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "urve.oja@example.com",
                            ExternalId = "S-1-5-21-10009",
                            Name = "Urve Oja",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "peeter.sepp@example.com",
                            ExternalId = "S-1-5-21-10010",
                            Name = "Peeter Sepp",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "markus.lepik@example.com",
                            ExternalId = "S-1-5-21-10011",
                            Name = "Markus Lepik",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "marta.laine@example.com",
                            ExternalId = "S-1-5-21-10012",
                            Name = "Marta Laine",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "anton.rebane@example.com",
                            ExternalId = "S-1-5-21-10013",
                            Name = "Anton Rebane",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "signe.kask@example.com",
                            ExternalId = "S-1-5-21-10014",
                            Name = "Signe Kask",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "riin.koppel@example.com",
                            ExternalId = "S-1-5-21-10015",
                            Name = "Riin Koppel",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "lauri.saar@example.com",
                            ExternalId = "S-1-5-21-10016",
                            Name = "Lauri Saar",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "viljar.laine@example.com",
                            ExternalId = "S-1-5-21-10017",
                            Name = "Viljar Laine",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "kristina.kroon@example.com",
                            ExternalId = "S-1-5-21-10018",
                            Name = "Kristina Kroon",
                            Source = "Windows",
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "system@example.srv",
                            ExternalId = "S-1-5-21-10000",
                            Name = "System",
                            Source = "Windows",
                            Type = 0
                        });
                });

            modelBuilder.Entity("Uptime.Workflows.Core.Data.WorkflowTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedById")
                        .HasColumnType("int");

                    b.Property<int>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedByPrincipalId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DeletedByPrincipalId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InternalStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhaseId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StorageJson")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TaskGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedByPrincipalId")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("PhaseId");

                    b.HasIndex("TaskGuid")
                        .IsUnique();

                    b.HasIndex("AssignedToId", "InternalStatus");

                    b.HasIndex("WorkflowId", "InternalStatus");

                    b.ToTable("WorkflowTasks", "UptimeAPI");
                });

            modelBuilder.Entity("Uptime.Workflows.Core.Data.WorkflowTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssociationDataJson")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedByPrincipalId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DeletedByPrincipalId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedByPrincipalId")
                        .HasColumnType("int");

                    b.Property<string>("WorkflowBaseId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("WorkflowTemplates", "UptimeAPI");
                });

            modelBuilder.Entity("Uptime.Workflows.Core.Data.Workflow", b =>
                {
                    b.HasOne("Uptime.Workflows.Core.Data.WorkflowPrincipal", "InitiatedBy")
                        .WithMany()
                        .HasForeignKey("InitiatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Uptime.Workflows.Core.Data.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("Workflows")
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InitiatedBy");

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("Uptime.Workflows.Core.Data.WorkflowHistory", b =>
                {
                    b.HasOne("Uptime.Workflows.Core.Data.WorkflowPrincipal", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Uptime.Workflows.Core.Data.Workflow", "Workflow")
                        .WithMany("WorkflowHistories")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedBy");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Uptime.Workflows.Core.Data.WorkflowTask", b =>
                {
                    b.HasOne("Uptime.Workflows.Core.Data.WorkflowPrincipal", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Uptime.Workflows.Core.Data.WorkflowPrincipal", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Uptime.Workflows.Core.Data.Workflow", "Workflow")
                        .WithMany("WorkflowTasks")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("AssignedTo");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Uptime.Workflows.Core.Data.Workflow", b =>
                {
                    b.Navigation("WorkflowHistories");

                    b.Navigation("WorkflowTasks");
                });

            modelBuilder.Entity("Uptime.Workflows.Core.Data.WorkflowTemplate", b =>
                {
                    b.Navigation("Workflows");
                });
#pragma warning restore 612, 618
        }
    }
}
