//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uptime.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkflowHistoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkflowHistoryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uptime.Shared.Resources.WorkflowHistoryResource", typeof(WorkflowHistoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tööülesanne on lõpule viidud.
        /// </summary>
        internal static string TaskCompleted {
            get {
                return ResourceManager.GetString("TaskCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tööülesanne on loodud.
        /// </summary>
        internal static string TaskCreated {
            get {
                return ResourceManager.GetString("TaskCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tööülesanne on kustutatud.
        /// </summary>
        internal static string TaskDeleted {
            get {
                return ResourceManager.GetString("TaskDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tööülesanne on muudetud.
        /// </summary>
        internal static string TaskModified {
            get {
                return ResourceManager.GetString("TaskModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tööülesanne on tagasivõetud.
        /// </summary>
        internal static string TaskRolledBack {
            get {
                return ResourceManager.GetString("TaskRolledBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Töövoog on tühistatud.
        /// </summary>
        internal static string WorkflowCancelled {
            get {
                return ResourceManager.GetString("WorkflowCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Töövoo kommentaar.
        /// </summary>
        internal static string WorkflowComment {
            get {
                return ResourceManager.GetString("WorkflowComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Töövoog on lõpetatud.
        /// </summary>
        internal static string WorkflowCompleted {
            get {
                return ResourceManager.GetString("WorkflowCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Töövoog on kustutatud.
        /// </summary>
        internal static string WorkflowDeleted {
            get {
                return ResourceManager.GetString("WorkflowDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Töövoo tõrge.
        /// </summary>
        internal static string WorkflowError {
            get {
                return ResourceManager.GetString("WorkflowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Töövoog on algatatud.
        /// </summary>
        internal static string WorkflowStarted {
            get {
                return ResourceManager.GetString("WorkflowStarted", resourceCulture);
            }
        }
    }
}
